/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafxx;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;


public class App extends Application{

    
        public static void main(String[] args){
            Application.launch(args);
        }
    
    @Override
    public void start(Stage stage) throws Exception{
        

        
        VBox vbox = new VBox();
        
       
        Label tittle = new Label ("Kalkulator Sehat");
        // tittle.getStyleClass().add("tittle");
        tittle.setFont(Font.font("Arial",30));
        tittle.setStyle("-fx-font-weight: bold; -f");
        vbox.getChildren().add(tittle);
        vbox.setSpacing(12.0);
        vbox.setStyle("-fx-background-color: #E8F6EF;");

        // Image logo = new Image(getClass().getClassLoader().getResourceAsStream("/image/timbangan.png"));
        ImageView calculatorLogo = new ImageView("/image/timbanganBiru.png");
        calculatorLogo.setFitWidth(254);
        calculatorLogo.setFitHeight(230);
        calculatorLogo.setPreserveRatio(true);
        calculatorLogo.setId("logo");
        

        
        

        Button startButton = new Button("Mulai");
        startButton.setMaxSize(100, 200);
        startButton.getStyleClass().add("startbutton");
        startButton.setMaxSize(100, 200);
        startButton.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");
        vbox.getChildren().addAll(calculatorLogo,startButton);
        vbox.setAlignment(Pos.CENTER);
        // startButton.setStyle("-fx-background-color: #FFC0CB; -fx-background-radius: 10;");
        startButton.setOnAction(action -> {
            // Seluruh kode diantara {} disini akan dijalankan / dieksekusi ketika button sedang di click.
                calculatorScene(stage);
        });
        


        Scene scene = new Scene(vbox,320, 512);
        
        stage.setScene(scene);
        stage.setTitle("Kalkulator keren");
        stage.show();
    }


    public void calculatorScene(Stage stage){
        VBox vbox = new VBox();
        Label tittle1 = new Label ("Pilih Kalkulator");
        tittle1.setFont(Font.font("Arial",25));
        tittle1.setStyle("-fx-font-weight: bold; -f");
        vbox.getChildren().add(tittle1);
        vbox.setSpacing(20.0);
        

        Button calculatorBMIButton = new Button("Kalkulator BMI");
        vbox.getChildren().add(calculatorBMIButton);
        vbox.setAlignment(Pos.CENTER);
        calculatorBMIButton.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");
        
        calculatorBMIButton.setOnAction(action -> {
            // Seluruh kode diantara {} disini akan dijalankan / dieksekusi ketika button sedang di click.
                BMICalculator(stage);
        });

        Button calculatorCalorieButton = new Button("Kalkulator kalori");
        vbox.getChildren().add(calculatorCalorieButton);
        vbox.setAlignment(Pos.CENTER);
        calculatorCalorieButton.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");
        
        calculatorCalorieButton.setOnAction(action -> {
            // Seluruh kode diantara {} disini akan dijalankan / dieksekusi ketika button sedang di click.
                gender(stage);
        });

        
        vbox.setStyle("-fx-background-color: #E8F6EF;");
        Scene scene = new Scene(vbox, 320, 512);
        stage.setScene(scene);
        stage.show();
    }

    public void BMICalculator(Stage stage){
        

        Label CalBMITittle = new Label("KALKULATOR BMI");
        CalBMITittle.setFont(Font.font("Arial",20));

        TextField weightTextField = new TextField();
        weightTextField.setPromptText("Berat badan");
        TextField heighTextField = new TextField();
        heighTextField.setPromptText("Tinggi badan");

        Button buttonCalculate = new Button("Calculate");
        buttonCalculate.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");
        Label BMIResult = new Label();

        Button buttonBack = new Button("Kembali");
        buttonBack.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");
        buttonBack.setOnAction(v->{
            calculatorScene(stage);
        });

        buttonCalculate.setOnAction(v->{
            
            try {
                double tinggi= Double.parseDouble(heighTextField.getText());
            tinggi=tinggi/100;
            double berat= Double.parseDouble(weightTextField.getText());
            double hasil = berat/(tinggi*tinggi);
            BMIResult.setText(String.format("%f", hasil));
                
            } catch (Exception e) {
                BMIResult.setText("Input salah");

            }
        });



        VBox vbox = new VBox(CalBMITittle, weightTextField,heighTextField,buttonCalculate, BMIResult,buttonBack);
        vbox.setPadding(new Insets(24));
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(12.0);
        vbox.setStyle("-fx-background-color: #E8F6EF;");


        
        Scene scene = new Scene(vbox, 320, 512);
        stage.setScene(scene);
        stage.show();
    }

    public void gender(Stage stage){

        Button perempuaButton = new Button("Perempuan");
        perempuaButton.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");
        perempuaButton.setOnAction(v->{
            calculatorCalorie(stage, false);
        });

        Button lakiButton = new Button("Laki-Laki");
        lakiButton.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");
        lakiButton.setOnAction(v->{
            calculatorCalorie(stage, true);
        });

        Button backButton = new Button("Kembali");
        backButton.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");
        backButton.setOnAction(v->{
            calculatorScene(stage);
        });

        VBox vbox = new VBox(perempuaButton, lakiButton,backButton);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(20.0);
        vbox.setStyle("-fx-background-color: #E8F6EF;");

        Scene scene = new Scene(vbox, 320, 512);
        stage.setScene(scene);
        stage.show();
    }

    public void calculatorCalorie(Stage stage, boolean isMale){

        Label judul2 = new Label("KALKULATOR KALORI");
        judul2.setFont(Font.font("Arial",20));

        TextField tfBeratK = new TextField();
        tfBeratK.setPromptText("Berat badan dalam kg");
        TextField tfTinggiK = new TextField();
        tfTinggiK.setPromptText("Tinggi dalam cm");
        TextField tfUmurK = new TextField();
        tfUmurK.setPromptText("Umur dalam tahun");

        Button calculate1 = new Button("calculate");
        calculate1.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");


        

        Label labelHasil1Label = new Label();
        calculate1.setOnAction(v->{
            try {
                double result;
                if (isMale==true){
                     result = 88.4 + 13.4 * Double.parseDouble(tfBeratK.getText()) +
                        4.8 * Double.parseDouble(tfTinggiK.getText()) - 5.68 * Double.parseDouble(tfUmurK.getText()) * 1.55;
                }
                else {
                     result = 447.6 + 9.25 * Double.parseDouble(tfBeratK.getText()) + 
                3.1 * Double.parseDouble(tfTinggiK.getText()) - 44.3 * Double.parseDouble(tfUmurK.getText()) * 1.375;
    
                }
                
                labelHasil1Label.setText(String.valueOf(result));
            } 
            catch (Exception e) {
                labelHasil1Label.setText("Input salah");
            }
        });
        Button buttonBack1 = new Button("Kembali");
        buttonBack1.setStyle("-fx-background-color: #4C4C6D; -fx-background-radius: 20; -fx-text-fill: white;");

        buttonBack1.setOnAction(v->{
            gender(stage);
        });
        


        VBox vbox = new VBox(judul2, tfBeratK, tfTinggiK, tfUmurK,calculate1, labelHasil1Label, buttonBack1);
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(12.0);
        vbox.setStyle("-fx-background-color: #E8F6EF;");
        vbox.setPadding(new Insets(24));

        Scene scene = new Scene(vbox, 320, 512);
        stage.setScene(scene);
        stage.show();
    }

    
}